language: node_js

node_js:
  - 8

env:
  - NODE_ENV=development

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

install:
  - yarn run build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: .out
  on:
    branch: master
